# Generated by Django 3.2.5 on 2021-08-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20210807_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='textarea',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
